version: '3.9'

services:

  rabbitmq:
    build: ./rabbitmq
    hostname: "localhost"
    ports:
      - '15672:15672'
      - '5672:5672'
      - '4369:4369'
    container_name: rabbitmq
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/app/rabbitmqdefinitions.json"
      
  song-request:
    build: './song-request-microsservice'
    ports:
      - '8080:8080'
    container_name: song-request
    depends_on:
      - rabbitmq

  song-player:
    build: './song-player-microsservice'
    ports:
      - '8081:8081'
    container_name: song-player
    depends_on:
      - rabbitmq
      - song-request

  song-logs:
    build: './song-logs-persistence-microsservice'
    ports:
      - '8082:8082'
    container_name: song-logs
    depends_on:
      - rabbitmq
      - song-request
      - song-player




     

    

  